version: "3.3"
services:

  # PHP APPS
  php_app:
    container_name: php_app
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
      args:
        - COMPOSER_VERSION=latest
        - XDEBUG_VERSION=latest
    volumes:
      - "php_app:/var/www/html"
      - "./logs/xdebug:/var/log/xdebug"
      - "./volumes/www-home:/home/www-data"
    networks:
      private:
    env_file: env/php.env

  # Supportive services
  
  packagist:
    image: packeton/packeton:latest
    restart: unless-stopped
    container_name: packagist
    hostname: packagist
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: 123456
      ADMIN_EMAIL: admin@example.com
    volumes:
      - ./volumes/satis:/data
    networks:
      public:
        ipv4_address: ${IP_BASE}.3

  nginx:
    image: nginx
    networks:
      private:
      public:
        ipv4_address: ${IP_BASE}.2
    volumes:
      - "php_app:/var/www/html"
      - "./test/php/index.php:/var/www/html/indes.php"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

volumes:
  php_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PHP_APP_PATH}
  
networks:
  private:
  public:
    ipam:
      config:
        - subnet: ${IP_BASE}.0/24
          gateway: ${IP_BASE}.1 