version: "3.8"
name: ${APP_NAME}

services:

  nginx:
    image: nginx
    networks:
      private:
      public:
        ipv4_address: ${IP_BASE}.2
    volumes:
      - "./www:/var/www/html"
      - "php_app_dist:/var/www/html/testlocal/dist"
      - "firebase_php:/var/www/firbase_php"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./ssl/certs/www.crt:/etc/nginx/ssl/www.crt:ro"
      - "./ssl/certs/www.key:/etc/nginx/ssl/www.key:ro"
  
  js-build:
    image: node:latest
    user: "${NODEJS_UID}:node"
    entrypoint: bash -c "ls -l && echo HELLO && npm install && npm start"
    working_dir: "/home/node/app"
    volumes:
      - "php_app:/home/node/app"
      - "./ssl/certs:/home/node/ssl:ro"

  firebasedemo:
    image: node:latest
    user: "${NODEJS_UID}:node"
    entrypoint: bash -c "ls -l && echo HELLO && npm install && npx parcel --https --port 443 --key=/home/node/ssl/www.key --cert=/home/node/ssl/www.crt --host ${IP_BASE}.3 src/index.html"
    working_dir: "/home/node/app"
    networks:
      public:
        ipv4_address: ${IP_BASE}.3
    volumes:
      - "./ssl.certs:/home/node/ssl"
      - "firebasedemo:/home/node/app"
      - "./ssl/certs:/home/node/ssl:ro"

  # PHP APPS
  php_app:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    networks:
      private:
    volumes:
      - "firebase_php:/var/www/firbase_php"
      - "./logs/xdebug:/var/log/xdebug"
      # Remove this line used for development only of xdebug tester 
      - "./utils/test_xdebug.php:/var/www/html/test_xdebug.php"
    environment:
      - APP_UID=1000
      - APP_GID=1000
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_PORT=9003
      - XDEBUG_ENABLE=TRUE
      - XDEBUG_DBGP=TRUE
    extra_hosts:
      host.docker.internal: host-gateway

volumes:

  php_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PHP_APP_PATH}

  php_app_dist:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PHP_APP_PATH}/dist
  
  firebasedemo:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${FIREBASEDEMO}
  
  firebase_php:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${FIREBASE_PHP}

networks:
  private:
  public:
    ipam:
      config:
        - subnet: ${IP_BASE}.0/24
          gateway: ${IP_BASE}.1 