version: "3.8"
name: ${APP_NAME}

services:

  # Supportive services
  
  nginx:
    image: nginx
    networks:
      private:
      public:
        ipv4_address: ${IP_BASE}.2
    volumes:
      - "php_app:/var/www/html"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./ssl/certs/www.crt:/etc/nginx/ssl/www.crt:ro"
      - "./ssl/certs/www.key:/etc/nginx/ssl/www.key:ro"

  js-build:
    container_name: esupport-frotnend-build
    image: node:latest
    user: "${NODEJS_UID}:node"
    entrypoint: bash -c "ls -l && echo HELLO && npm install && npm run start"
    working_dir: "/home/node/app"
    volumes:
      - "php_app:/home/node/app"

volumes:

  php_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PHP_APP_PATH}
  
networks:
  private:
  public:
    ipam:
      config:
        - subnet: ${IP_BASE}.0/24
          gateway: ${IP_BASE}.1 