version: "3.3"
services:

  # PHP APPS
  php_app:
    container_name: php_app
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
      args:
        - COMPOSER_VERSION=latest
        - XDEBUG_VERSION=latest
        - PHP_VERSION=8.2
    volumes:
      - "php_app:/var/www/html"
      - "./conf/php/conf.d:/usr/local/etc/php/conf.d"
      - "./logs/xdebug:/var/log/xdebug"
      - "./ssl/ca/ca.crt:/usr/local/share/cert_install/ca.crt"
      - "./volumes/www-home:/home/www-data"
    networks:
      private:
    env_file: env/php.env

  js-build:
    image: node:latest
    user: "${UID}:node"
    entrypoint: bash -c "npm install && npm run build_dev"
    working_dir: "/home/node/app"
    volumes:
      - "php_app:/home/node/app"

  # Supportive services
  
  nginx:
    image: nginx
    networks:
      private:
      public:
        ipv4_address: ${IP_BASE}.2
    volumes:
      - "php_app:/var/www/html"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./ssl/certs/www.crt:/etc/nginx/ssl/www.crt:ro"
      - "./ssl/certs/www.key:/etc/nginx/ssl/www.key:ro"

  mssql:
    # Replace with your own
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    networks:
      private:
      public:
        ipv4_address: ${IP_BASE}.3
    command: bash -c "chmod -R 777 /usr/src/sql/ && /opt/mssql/bin/sqlservr"
    volumes:
      - ./volumes/db/data:/var/opt/mssql/data
      - ./volumes/db/log:/var/opt/mssql/log
      - ./sql:/usr/src/sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "T3stpsswd"
      MSSQL_PID: "Developer"

volumes:

  php_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PHP_APP_PATH}
  
networks:
  private:
  public:
    ipam:
      config:
        - subnet: ${IP_BASE}.0/24
          gateway: ${IP_BASE}.1 