version: "3.3"
services:

  # PHP APPS
  php_app:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    volumes:
      - "php_app:/var/www/html"
      - "./logs/xdebug:/var/log/xdebug"
    networks:
      private:
    environment:
      - APP_UID=1000
      - APP_GID=1000
      - XDEBUG_IDE_KEY=PHPSTORM
      - XDEBUG_PORT=9003
      - XDEBUG_ENABLE=TRUE
      - XDEBUG_DBGP=TRUE


  # Supportive services
  
  nginx:
    image: nginx
    networks:
      private:
      public:
        ipv4_address: ${IP_BASE}.2
    volumes:
      - "php_app:/var/www/html"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

  mariadb:
    # Replace with your own
    image: mariadb:10.4
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    networks:
      private:
      public:
        ipv4_address: ${IP_BASE}.3
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

volumes:

  dbdata:

  php_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PHP_APP_PATH}
  
networks:
  private:
  public:
    ipam:
      config:
        - subnet: ${IP_BASE}.0/24
          gateway: ${IP_BASE}.1 